{% set name = "ryp" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ryp-{{ version }}.tar.gz
  sha256: d120624eee2074e6b6df4b51cbd40394861c921000c0e43d973fd62c81436ebf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - cffi
    - pyarrow
    - r-base
    - r-arrow

test:
  imports:
    - ryp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ryp
  summary: R inside Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Wainberg
